### ISSUE TITLE
RuntimeError: 0D or 1D target tensor expected, multi-target not supported

### ISSUE THREAD

**Issue by Hasindri** [WinnieLaugh/StructuredTriplet#1]
I am trying to obtain evaluation results on PanNuke dataset from the model pre-trained on LarSPI. I am running code on Google Colab. I am using PanNuke dataset downloaded from kaggle, please let me know if there is any issue with this dataset.

using the following command I am running 'linear_eval.py' file,

`!python tools/linear_eval.py --root_eval '/content/StructuredTriplet/dataset' --name 'test1'
`

but I am getting the following error,

```
/usr/local/lib/python3.7/dist-packages/torchvision/transforms/functional.py:418: UserWarning: Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. Please use InterpolationMode enum.
  "Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. "
tcmalloc: large alloc 1113587712 bytes == 0x7f4b17a00000 @  0x7f4c7ee741e7 0x7f4c0e72b0ce 0x7f4c0e787715 0x7f4c0e787d1b 0x7f4c0e828333 0x58f62c 0x5105e2 0x58fd37 0x50c4fc 0x58fd37 0x50c4fc 0x58fd37 0x50c4fc 0x5b4ee6 0x6005a3 0x607796 0x60785c 0x60a436 0x64db82 0x64dd2e 0x7f4c7ea71c87 0x5b636a
Features shape (2124, 512)
Features shape (532, 512)
**output shape (512,5)
gt_labels shape (512,256,256)**
Traceback (most recent call last):
  File "tools/linear_eval.py", line 150, in <module>
    linear_eval_train(1)
  File "tools/linear_eval.py", line 97, in linear_eval_train
    **loss = cross_entropy_loss(output, gt_labels)**
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py", line 1166, in forward
    label_smoothing=self.label_smoothing)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py", line 3014, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: 0D or 1D target tensor expected, multi-target not supported

```

I believe error is due to the way I am making the needed **train.txt, train.npy, test.txt, test.npy** files. They were not provided in your repository, **it would be really helpful if you can upload them** to get an understanding on their data format. I created those files using following code,

```
out_dir = "./"

def flat_for(a, f):
    a = a.reshape(-1)
    # [6, 7, 7, 4, 5, 7]

    for i, v in enumerate(a):
      a[i] = f(v)   # map instances to new indices according to the dict
    # we get [2, 3, 3, 0, 1, 3]
    
    return a

# map instance segmentation values to values [0, N1, N2, .. Nx] 
# to values in the range 0, len(unique instance values)
def map_inst(inst):
    # let inst be array([[6., 7., 7.], [4., 5., 7.]])
    seg_indexes = np.unique(inst)  # get all the unique values in the inst (concatenated masks)
    # we get 4, 5, 6, 7
    new_indexes = np.array(range(0, len(seg_indexes)))
    # we get 0, 1, 2, 3
    dict = {}
    for seg_index, new_index in zip(seg_indexes, new_indexes):
      dict[seg_index] = new_index  # map segmentation indices to new indices
    # we get {4:0, 5:1, 6:2,7:3}

    inst_copy = flat_for(inst.copy(), lambda x: dict[x])
    # we get a flattened array of mask values, mapped for indexes from 0 - len(unique values in the mask)
    return inst_copy

def transform(images, masks, path, start, finish):

    train_imgs = []    
    
    start = int(images.shape[0]*start)
    finish = int(images.shape[0]*finish)
    np_file_final = []

    os.mkdir('/content/StructuredTriplet/dataset/PanNuke/img/' + path)
    os.mkdir('/content/StructuredTriplet/dataset/PanNuke/mask/' + path)
    img_idx = 0
    
    for i in tqdm(range(start, finish)):
      # np_file = np.zeros((256, 256, 4), dtype='int16')
      np_file = []
      dataset_idx = 1
      np_file.append(dataset_idx)
      np_file.append(img_idx)
      img_idx += 1
      im = Image.fromarray(images[i].astype(np.uint8))

      
      im.save('/content/StructuredTriplet/dataset/PanNuke/img/' + path + '/'  + str(i) + '.jpg')
      train_imgs.append(path + '/' +str(i) + '.jpg')

      msk = masks[i]

      inst = np.zeros((256,256))
      for j in range(5):
        #copy value from new array if value is not equal 0
        inst = np.where(msk[:,:,j] != 0, msk[:,:,j], inst)
        # mak[:, :, j] is a (256, 256) array
        # if each element in msk[:, :, j] has a value, replace inst at that index with that value
        # if an element in msk[:, :, j] at an index is 0, don't change the value of inst at that index
        # with this, we get an array with all cell masks (as cells don't overlap (most of the time), we won't have a problem)

      #inst_copy = map_inst(inst)
      # we get a flattened array of mask values, mapped for indexes from 0 - len(unique values in the mask)
      # in this case, an array of 
      np_file.append(inst)

      np.save('/content/StructuredTriplet/dataset/PanNuke/mask/' + path + '/'  + str(i) + '.npy', inst)

      types = np.zeros((256,256))
      for j in range(5):
        # write type index if mask is not equal 0 and value is still 0
        types = np.where((msk[:,:,j] != 0) & (types == 0), j+1, types)
        # here, we can get values in 1-5 for type
        # if mask slice element at index has a value, and the type array does not have a value at that point, replace it with j+1
        # j+1 increment because each mask is for one type of nuclei
        # as cells don't overlap, we won't have a problem
      
      np_file.append(types)

      np_file_final.append(np_file)
      

    file_path = '/content/StructuredTriplet/dataset/PanNuke/' + path + '.txt'
    npy_path = '/content/StructuredTriplet/dataset/PanNuke/' + path + '.npy'
    
    with open(file_path, 'w') as fm:
      for image_file in train_imgs:
        fm.write(f'{image_file}\n')

    np.save(npy_path, np_file_final)
    return np_file_final

# create img/train folder in panNuke in repo dataset folder
```

using above functions, files are created as follows,

```
np_final = transform(images, masks, 'train', start=0, finish=0.8)
np_final = transform(images, masks, 'test', start=0.8, finish=1)
```

test files can be made similarly. according to this my 'train.txt' file contains data paths of format 'train/0001.jpg'. Issue comes with 'train.npy' file which I create as a large numpy array of training set size, each having 4 elements. first is the dataset index of PanNuke, second is the image index and third is the 256x256 mask array where all 5 nuclei type masks are combined. as error comes from data shape mismatch of output(of model) and labels(type labels I give), issue should be with how I add the fourth element which I add as a 256x256 array consisting of type index at each position. Looking at output, it looks like this type should be a scalar value. Can you clarify on this?

thank you.

**Comment by WinnieLaugh** [comment]
Sorry about that! I forgot to upload the txt and npy files for the evaluation datasets. I am digging into my old code and will upload them today.

**Comment by WinnieLaugh** [comment]
Hi @Hasindri ,

I have uploaded the npy and txt files for evaluation now. You can have a try at it!

You can now download the CoNSeP and panNuke datasets first, convert them into the format as like: 

{root_dir}/CoNSeP/img/Train
{root_dir}/CoNSeP/img/Test
{root_dir}/CoNSeP/mask/Train
{root_dir}/CoNSeP/mask/Test

where the masks are instance maps of size 1000x1000, with 0 as the background and n>1 as the instance id, which is basically the 'inst_map' item of the original data. 

And then run the `python tools/linear_eval.py` with the new uploaded npy and txt files.

Since I don't have the permission to re-distribute those datasets, I could not upload my own processed ones for simpler usage. But I believe it won't be too hard to write the processing code. I will also clean up my data-process code as soon as I got some time, probably next week when I settle down in my new home.

Best,
Wenhua

**Comment by Hasindri** [comment]
Hi Wenhua,

Thank you very much for the quick response. I will try with the files you uploaded.

Best regards,
Hasindri
